project_id = "buriwmeuvujisgmqnpjr"

[functions.dna-webhook]
verify_jwt = false

[functions.onboard-client]
verify_jwt = false

[functions.send-dossier-email]
verify_jwt = false

[functions.fire-email-1]
verify_jwt = false

[functions.fire-email-2]
verify_jwt = false

[functions.fire-email-3]
verify_jwt = false

[functions.fire-email-4]
verify_jwt = false

[functions.stage6-runner]
verify_jwt = false
